#
#Mon Jun 01 01:46:58 PET 2026
goog\:chromeOptions={args\=[--headless, --no-sandbox, --disable-gpu, --window-size\=1280,800, --remote-allow-origins\=*, --headless], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
